# Generated by Django 2.0.4 on 2018-04-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luffy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricepolicy',
            options={'verbose_name': '价格策略', 'verbose_name_plural': '价格策略'},
        ),
        migrations.AlterField(
            model_name='degreecourse',
            name='brief',
            field=models.TextField(blank=True, null=True, verbose_name='学位课程简介'),
        ),
        migrations.AlterField(
            model_name='degreecourse',
            name='course_img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='brief',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='职位、职称'),
        ),
    ]
